services:
  
  aerospike-graph-service:
    image: aerospike/aerospike-graph-service:3.0.0
    container_name: asgraph-service
    depends_on:
      zipkin:
        condition: service_healthy
    volumes:
      - ./data:/data
      - ./tls:/opt/aerospike-graph/aerospike-client-tls:ro
    environment:
      - aerospike.client.namespace=${AEROSPIKE_NAMESPACE:-test}
      - aerospike.client.host=${AEROSPIKE_HOST}
      - aerospike.client.port=${AEROSPIKE_KV_PORT:-4000}
      - aerospike.client.tls=true
      - aerospike.client.user=${AEROSPIKE_USER}
      - aerospike.client.password=${AEROSPIKE_PASSWORD}
      - aerospike.client.auth.mode=INTERNAL
      - aerospike.graph.index.vertex.label.enabled=true
      - aerospike.graph.query-tracing.threshold-ms=5
      - aerospike.graph.query-tracing.opentelemetry-host=zipkin
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 4
    networks:
      - asgraph_net
    ports:
      - "8182:8182"
      - "9090:9090"
  zipkin:
    image: openzipkin/zipkin
    container_name: asgraph-zipkin
    networks:
      - asgraph_net
    ports:
      - "9411:9411"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 5s
      timeout: 10s
      retries: 4
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: "asgraph-backend"
    depends_on:
      # aerospike-db:
      #   condition: service_healthy
      aerospike-graph-service:
        condition: service_healthy
    environment:
      - AEROSPIKE_HOST=${AEROSPIKE_HOST}
      - AEROSPIKE_KV_PORT=${AEROSPIKE_KV_PORT:-4000}
      - AEROSPIKE_NAMESPACE=${AEROSPIKE_NAMESPACE:-test}
      - AEROSPIKE_TLS_ENABLE=${AEROSPIKE_TLS_ENABLE:-true}
      - AEROSPIKE_TLS_NAME=${AEROSPIKE_TLS_NAME}
      - AEROSPIKE_TLS_CAFILE=${AEROSPIKE_TLS_CAFILE:-/tls/ca.pem}
      - AEROSPIKE_USER=${AEROSPIKE_USER}
      - AEROSPIKE_PASSWORD=${AEROSPIKE_PASSWORD}
      - GRAPH_HOST_ADDRESS=asgraph-service
    volumes:
      - ./data:/data
      - ./tls:/tls
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:4000/health"]
      interval: 5s
      timeout: 10s
      retries: 4
    networks:
      - asgraph_net
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: "asgraph-frontend"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - BACKEND_URL=http://asgraph-backend:4000
    networks:
      - asgraph_net
    ports:
      - "8080:8080"
  generator:
    build:
      context: .
      dockerfile: generator.Dockerfile
    container_name: "asgraph-generator"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - asgraph_net
    ports:
      - "4001:4001"

networks:
  asgraph_net:
    name: asgraph_net
